apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: docker.io/pappydockerhub/udagram-api-user:v2
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST
              value: "database-1.czi5uc0onyww.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          envFrom:
            - configMapRef:
                name: udagram-configmap
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
