apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
  labels:
    run: udagram-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: udagram-frontend-service